# Generated by Django 3.2.4 on 2021-09-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jipasApi', '0004_auto_20210908_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
