# Generated by Django 3.2.4 on 2021-09-08 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jipasApi', '0005_alter_comment_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
