# Generated by Django 3.2.7 on 2021-09-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jipasApi', '0006_remove_comment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('Notification', models.TextField()),
                ('fromId', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=50)),
            ],
        ),
    ]
