# Generated by Django 3.2.7 on 2021-09-18 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jipasApi', '0008_notificationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtoken',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='token', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationtoken',
            name='token',
            field=models.CharField(max_length=40),
        ),
    ]
